### ISSUE TITLE
Error: splib3 not found

### ISSUE THREAD

**Issue by WilliamHangXu** [SofaDefrost/SofaGym#54]
Hi all, I just installed SofaGym. I tried to run the test_env.py file and got this error:

Traceback (most recent call last):
  File "test_env.py", line 23, in <module>
    from sofagym.envs import *
  File "/home/william/SofaGym/sofagym/envs/__init__.py", line 1, in <module>
    from sofagym.envs.BubbleMotion.BubbleMotionEnv import *
  File "/home/william/SofaGym/sofagym/envs/BubbleMotion/BubbleMotionEnv.py", line 11, in <module>
    from sofagym.AbstractEnv import AbstractEnv
  File "/home/william/SofaGym/sofagym/AbstractEnv.py", line 20, in <module>
    import splib3
ModuleNotFoundError: No module named 'splib3'

I have installed all the plugins listed in README. Any idea how I should fix this? Thank you!

**Comment by jiayiliu-pku** [comment]
Hi, I also had this problem, but I changed all 'splib3' to 'splib'. It seems work. You may try it.

**Comment by samuelmyoussef** [comment]
Hello,

sorry for the late reply. You need to add where `splib3` is to your `PYTHONPATH` like this:
`export PYTHONPATH=$SOFA_ROOT/lib/python3/site-packages:$PYTHONPATH`

**Comment by alxbilger** [comment]
See also discussion https://github.com/sofa-framework/sofa/discussions/4511

**Comment by WilliamHangXu** [comment]
Thank you! I fixed the issue by adding the path of `splib3` into `PYTHONPATH`: `plugins/STLIB/lib/python3/site-packages`
