### ISSUE TITLE
The object 'CableConstraint' is not in the factory.

### ISSUE THREAD

**Issue by jiayiliu-pku** [SofaDefrost/SofaGym#57]
After installation of all requirements, I tried to perform tests.
`python test_env.py -e trunk-v0 -ep 100 -s 100`
However, I got this error:
![image](https://github.com/SofaDefrost/SofaGym/assets/52529439/4b35595c-6212-4afe-83a7-f4b67280f653)

Could you help me with it?

Thanks.

**Comment by alxbilger** [comment]
`CableConstraint` is part of the `SoftRobots` plugin. Do you have it? Did you load it?

**Comment by jiayiliu-pku** [comment]
> `CableConstraint` is part of the `SoftRobots` plugin. Do you have it? Did you load it?

I have it and load it in the Sofa-GUI with plugin manager. However I still get the same error.

**Comment by jiayiliu-pku** [comment]
> Hello,
> 
> I'm not exactly sure but it might be a problem with your build. Could you give more details about this?

For SOFA build: I followed https://www.sofa-framework.org/community/doc/getting-started/build/linux
For other plugins, I use out-of-tree method to build them.
I am not sure how to provide details about it.

If more details are needed, please tell me.

**Comment by jiayiliu-pku** [comment]
I have re-installed the Sofa and required plugins with in-tree build.

I added the following two lines in CMakeLists.txt in sofa/src to fix the bug (`error: 'is_same_v' is not a member of 'std'`)
`set(CMAKE_CXX_STANDARD 17)`
`set(CMAKE_CXX_STANDARD_REQUIRED ON)`

Then, I added required plugins using plugin manager. 

The bug was fixed :)
